# Snakefile

# Load configuration
configfile: "config/config.yaml"

# Include the separate rule files
include: "rules/fasta.smk"
include: "rules/reference_files.smk"
include: "rules/alignment.smk"
include: "rules/feature_counts.smk"
include: "rules/visualization.smk"

# Targets
rule all:
    input:
        "plots/gene_expression_barplot.png"