accession: 
  - SRR13442908

star_index: "data/refs/star_index"
genome_fasta_gz: "data/refs/GRCh38.p13.genome.fa.gz"  
genome_fasta: "data/refs/GRCh38.p13.genome.fa"
gtf_annotation_gz: "data/refs/gencode.v38.annotation.gtf.gz"
gtf_annotation: "data/refs/gencode.v38.annotation.gtf"
genome_fasta_url: "ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_38/GRCh38.p13.genome.fa.gz"
gtf_annotation_url: "ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_38/gencode.v38.annotation.gtf.gz"
read_length: 100
threads_index: 3